// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function GetChatMessages() {
  return window['go']['main']['App']['GetChatMessages']();
}

export function GetLoadingProgress() {
  return window['go']['main']['App']['GetLoadingProgress']();
}

export function GetLoadingStage() {
  return window['go']['main']['App']['GetLoadingStage']();
}

export function IsModelLoaded() {
  return window['go']['main']['App']['IsModelLoaded']();
}

export function LoadModel(arg1) {
  return window['go']['main']['App']['LoadModel'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['main']['App']['OnShutdown'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function UnloadModel() {
  return window['go']['main']['App']['UnloadModel']();
}
