// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortStream() {
  return window['go']['main']['App']['AbortStream']();
}

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function ClearChatHistory() {
  return window['go']['main']['App']['ClearChatHistory']();
}

export function GetChatMessages() {
  return window['go']['main']['App']['GetChatMessages']();
}

export function GetLoadedModelName() {
  return window['go']['main']['App']['GetLoadedModelName']();
}

export function GetLoadingProgress() {
  return window['go']['main']['App']['GetLoadingProgress']();
}

export function GetLoadingStage() {
  return window['go']['main']['App']['GetLoadingStage']();
}

export function GetModelOptions() {
  return window['go']['main']['App']['GetModelOptions']();
}

export function GetModelsDir() {
  return window['go']['main']['App']['GetModelsDir']();
}

export function GetSamplerSettings() {
  return window['go']['main']['App']['GetSamplerSettings']();
}

export function IsModelLoaded() {
  return window['go']['main']['App']['IsModelLoaded']();
}

export function LoadModel(arg1) {
  return window['go']['main']['App']['LoadModel'](arg1);
}

export function LoadModelMetadata(arg1) {
  return window['go']['main']['App']['LoadModelMetadata'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['main']['App']['OnShutdown'](arg1);
}

export function OpenModelFilePicker() {
  return window['go']['main']['App']['OpenModelFilePicker']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SendMessageStream(arg1) {
  return window['go']['main']['App']['SendMessageStream'](arg1);
}

export function SendMessageStreamWithImage(arg1, arg2) {
  return window['go']['main']['App']['SendMessageStreamWithImage'](arg1, arg2);
}

export function SetModelOptions(arg1) {
  return window['go']['main']['App']['SetModelOptions'](arg1);
}

export function SetSamplerSettings(arg1) {
  return window['go']['main']['App']['SetSamplerSettings'](arg1);
}

export function UnloadModel() {
  return window['go']['main']['App']['UnloadModel']();
}

export function UpdatePromptSettings(arg1) {
  return window['go']['main']['App']['UpdatePromptSettings'](arg1);
}

export function UpdateRuntimeSettings(arg1) {
  return window['go']['main']['App']['UpdateRuntimeSettings'](arg1);
}
