// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ClearChat():Promise<void>;

export function GetChatMessages():Promise<Array<Record<string, any>>>;

export function GetLoadingProgress():Promise<number>;

export function GetLoadingStage():Promise<string>;

export function IsModelLoaded():Promise<boolean>;

export function LoadModel(arg1:string):Promise<void>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function SendMessage(arg1:string):Promise<string>;

export function UnloadModel():Promise<void>;
