// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function AbortStream():Promise<void>;

export function ClearChat():Promise<void>;

export function ClearChatHistory():Promise<void>;

export function GetChatMessages():Promise<Array<Record<string, any>>>;

export function GetLoadedModelName():Promise<string>;

export function GetLoadingProgress():Promise<number>;

export function GetLoadingStage():Promise<string>;

export function GetModelOptions():Promise<Record<string, any>>;

export function GetModelsDir():Promise<string>;

export function GetSamplerSettings():Promise<Record<string, any>>;

export function IsModelLoaded():Promise<boolean>;

export function LoadModel(arg1:string):Promise<void>;

export function LoadModelMetadata(arg1:string):Promise<types.ModelProfile>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OpenModelFilePicker():Promise<string>;

export function SendMessage(arg1:string):Promise<string>;

export function SendMessageStream(arg1:string):Promise<void>;

export function SendMessageStreamWithImage(arg1:string,arg2:string):Promise<void>;

export function SetModelOptions(arg1:Record<string, any>):Promise<void>;

export function SetSamplerSettings(arg1:Record<string, any>):Promise<void>;

export function UnloadModel():Promise<void>;

export function UpdatePromptSettings(arg1:types.PromptSettings):Promise<void>;

export function UpdateRuntimeSettings(arg1:types.RuntimeSettings):Promise<void>;
